[package]
name = "v021_app_builder"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5.27", features = ["derive"] }
tokio = { version = "1.37", features = ["full"] }

